AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RootUsername:
    Type: String

  RootPassword:
    Type: String
    NoEcho: True

  AllocatedStorage:
    Type: Number
    Default: 5

  BackupRetention:
    Type: Number
    Default: 1

  HostedZoneName:
    Type: String

  DbSubdomain:
    Type: String
    Default: db
    Description: Route53 subdomain to prepend to HostedZoneName

Resources:
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties: 
      Comment: Shared App DB DNS Record
      HostedZoneName: !Sub '${HostedZoneName}.'
      Name: !Sub '${DbSubdomain}.${HostedZoneName}'
      ResourceRecords: 
        - !GetAtt Instance.Endpoint.Address
      TTL: 300
      Type: CNAME

  Instance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: '15.4'
      MasterUsername: !Ref 'RootUsername'
      MasterUserPassword: !Ref 'RootPassword'
      Port: 5432
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: !Ref 'AllocatedStorage'
      BackupRetentionPeriod: !Ref 'BackupRetention'
      DeletionProtection: True
      StorageEncrypted: True
      VPCSecurityGroups:
        - !ImportValue DBSecurityGroupId

Outputs:
  DbUri:
    Value: !Sub '${DbSubdomain}.${HostedZoneName}'

  RootUsername:
    Value: !Ref 'RootUsername'

  Port:
    Value: '5432'

  DbInstanceId:
    Value: !Ref Instance
